# name: Test AWS connection

# on:
#   workflow_dispatch:

# permissions:
#   id-token: write
#   contents: read

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Connect GitHub to AWS
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           role-to-assume: ${{ vars.AWS_ROLE_ARN }}
#           aws-region: ${{ vars.AWS_REGION }}

#       - name: Show connected AWS account
#         run: aws sts get-caller-identity


- name: Show safe OIDC details
        uses: actions/github-script@v8
        with:
          script: |
            const token = await core.getIDToken('sts.amazonaws.com');
            const claims = JSON.parse(
              Buffer.from(token.split('.')[1], 'base64url').toString()
            );
            console.log({
              sub: claims.sub,
              aud: claims.aud,
              repository: claims.repository,
              ref: claims.ref,
              event_name: claims.event_name
            });